spring.application.name=digital-wallet

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
server.port=8080

jwt.secret=${JWT_SECRET}

anomaly.large-amount-threshold=50000
anomaly.high-amount-threshold=10000
anomaly.frequency-threshold=5
anomaly.frequency-window-minutes=60


ai.provider=gemini
gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-3.6-flash